POST http://localhost:5000/Scores
Content-Type: application/json

{
    "name": "Knyga",
    "score": 150
}
###

GET http://mongodb+srv://ksimkevicius01:GnijTy7YdF9Ku4RW@cluster0.2efpicy.mongodb.net/getscores